### PR TITLE
Hero section adarsh

### PR DESCRIPTION
**Pull request by yousant**

### CODE REVIEW

**Comment by yousant** [comment]
main view
image

**Comment by yousant** [comment]
video

https://github.com/gdsc-nits-org/tecnoesis-web/assets/97018523/c49414a1-e234-4fe8-bafc-10478cb0fd2e

**Comment by yousant** [comment]
tablet view
image

**Comment by yousant** [comment]
mobile view
image

**Review by username-naz — CHANGES_REQUESTED** [review]
- Remove tailwind and postcss.
- remove junk from app.jsx. your code should be in a component that you import into home page.
- move images to public folder. create another folder inside it to keep things clean.
- configure lottie file to be displayed properly according to the design.
- fix the css. elements are overflowing the screen. hero section should not be long enough to pop up a scroll bar.
- name your commit messages properly. read the instructions given again or ask someone who knows.
- use css variables written in app.css for colors
- remove unnecessary comments

**Comment by yousant** [comment]
The lotties of pacman are not given by UI/UX team there is some glitch in lottie, so i have used this lottie from web.

**Review by username-naz — CHANGES_REQUESTED** [review]
image
incorrect import. fix it

**Review by username-naz — CHANGES_REQUESTED** [review]
image
incorrect import syntax from public folder

**Review by username-naz — CHANGES_REQUESTED** [review]
image
pacman is overlapping with arrow

**Review by username-naz — CHANGES_REQUESTED** [review]
Add:
- smooth scrolling
- lazy loading for background

**Comment by codadept** [comment]
image

This problem is for screen sizes of width 1024px to 1280px. And this is because you are using top property to control the position. This is not the correct approach.

**Review by username-naz — APPROVED** [review]

**Pull request merged**
